// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2wMQVHuFnFkOXk1hkEKi7ld25hd-UL9w',
    appId: '1:925803349083:web:8c671c8230299a8f092b7e',
    messagingSenderId: '925803349083',
    projectId: 'quizzyy-2ccb9',
    authDomain: 'quizzyy-2ccb9.firebaseapp.com',
    databaseURL: 'https://quizzyy-2ccb9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizzyy-2ccb9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmQf60Aj6uixFZyPjFb61jDzUMESy2HCU',
    appId: '1:925803349083:android:685617bd2a616f6b092b7e',
    messagingSenderId: '925803349083',
    projectId: 'quizzyy-2ccb9',
    databaseURL: 'https://quizzyy-2ccb9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizzyy-2ccb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7wvQjYRgZJ52ukL1__gDp5tBCsiQVFtA',
    appId: '1:925803349083:ios:cdf0bc30f8d31fd9092b7e',
    messagingSenderId: '925803349083',
    projectId: 'quizzyy-2ccb9',
    databaseURL: 'https://quizzyy-2ccb9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizzyy-2ccb9.appspot.com',
    iosBundleId: 'com.example.quizzbuzz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7wvQjYRgZJ52ukL1__gDp5tBCsiQVFtA',
    appId: '1:925803349083:ios:cdf0bc30f8d31fd9092b7e',
    messagingSenderId: '925803349083',
    projectId: 'quizzyy-2ccb9',
    databaseURL: 'https://quizzyy-2ccb9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizzyy-2ccb9.appspot.com',
    iosBundleId: 'com.example.quizzbuzz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2wMQVHuFnFkOXk1hkEKi7ld25hd-UL9w',
    appId: '1:925803349083:web:d0d6431e47420436092b7e',
    messagingSenderId: '925803349083',
    projectId: 'quizzyy-2ccb9',
    authDomain: 'quizzyy-2ccb9.firebaseapp.com',
    databaseURL: 'https://quizzyy-2ccb9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizzyy-2ccb9.appspot.com',
  );

}